site_name: SIGAA
pages:
  - Home: 'index.md'
  - Planejamento: 'planejamento/planejamento.md'
  - Análise do Perfil de Usários: 
    - Questionário: 'perfil-usuario/questionario.md'
    - Entrevista: 'perfil-usuario/entrevista.md'
    - Persona: 'perfil-usuario/persona.md'
  - Análise de tarefas: 'analise-de-tarefas/analise.md'  
  - Avaliação Heurística: 'avaliacao-heuristica/avaliacao.md'
  - Prototipo de Papel: 'Prototipo-de-Papel/prototipo_de_papel.md'
  - Metas de Usabilidade: 'metas-de-usabilidade/metas.md'
  - Lista de sites avaliados: 'sites-avaliados/sites.md' 
  - Processo de Design: 'processo-de-design/processo.md'
extra_css: 
  - assets/css/extra.css
theme:
  name: material
  language: pt

repo_name: 'Repositório'
repo_url: 'https://github.com/Interacao-Humano-Computador/2020.1-SIGAA'
