site_name: SIGAA
pages:
  - Home: 'index.md'
  - Planejamento: 
    - Heatmap e Roadmap: 'planejamento/planejamento.md'  
    - Sites Avaliados: 'planejamento/sites-avaliados/sites.md'
    - Processo de Design: 'planejamento/processo-de-design/processo.md'
  - Análise do Perfil de Usários: 
    - Questionário: 'perfil-usuario/questionario.md'
    - Entrevista: 'perfil-usuario/entrevista.md'
    - Persona: 'perfil-usuario/persona.md'
  - Análise de tarefas: 
    - Análise de tarefas: 'analise-de-tarefas/analise.md'
    - Planejamento da Avaliação de tarefas: 'planejamentoAvaliacao/PlHTA.md'
    - Resultado da Avaliação de tarefas: 'ResulAnalise/analise.md'
  - Principios Gerais: 'principios-gerais.md'
  - Guia de estilo: 'guia-de-estilo.md'
  - Análise de requisitos:
    - Metas de usabilidade: 'metas-de-usabilidade/metas.md'
  - Storyboard: 
    - Storyboard: 'design-e-avalicao/storyboard.md'
    - Planejamento da Avaliação do StoryBoard: 'planejamentoAvaliacao/PlStoryBoard.md'
    - Resultado da Avaliação do Storyboard: 'ResulStoryboard/story.md'
  - Apresentações: 'apresentacoes/apresentacoes.md'
  
extra_css: 
  - assets/css/extra.css
theme:
  name: material
  language: pt

repo_name: 'Repositório'
repo_url: 'https://github.com/Interacao-Humano-Computador/2020.1-SIGAA'
