site_name: SIGAA
pages:
  - Home: 'index.md'
  - Planejamento: 
    - Heatmap e Roadmap: 'planejamento/planejamento.md'  
    - Sites Avaliados: 'planejamento/sites-avaliados/sites.md'
    - Processo de Design: 'planejamento/processo-de-design/processo.md'
  - Análise do Perfil de Usários: 
    - Questionário: 'perfil-usuario/questionario.md'
    - Entrevista: 'perfil-usuario/entrevista.md'
    - Persona: 'perfil-usuario/persona.md'
  - Análise de tarefas: 'analise-de-tarefas/analise.md'
  - Apresentações: 'apresentacoes/apresentacoes.md'
extra_css: 
  - assets/css/extra.css
theme:
  name: material
  language: pt

repo_name: 'Repositório'
repo_url: 'https://github.com/Interacao-Humano-Computador/2020.1-SIGAA'
